fix(test): Disable grpc metrics to avoid otel plugin error log in integration tests. (#4266)
### Description
Disable **grpc** metrics to avoid **otel** plugin error log in integration tests. 
**ERROR: [otel-plugin] ctx passed into client side stats handler metrics event handling has no client attempt data present**
is logged when running any integration tests with grpc protocol and is a known issue in otel grpc plugin and we already disabled grpc metrics in production, doing the same for storage client creation for tests to ensure the noise from this logs removed in tests as well.

### Link to the issue in case of a bug fix.
b/475117270

### Testing details
1. Manual
Go to the directory:
cd ~/gcsfuse/tools/integration_tests/buffered_read .
Run the bufferred read package integration tests.
go test . -test.timeout 5400s -test.parallel 1 --integrationTest -test.v --testbucket=thrivikramks_test_runs_zb --zonal=true -test.count 1

without changes in this PR, you would see logs like 
ERROR: [otel-plugin] ctx passed into client side stats handler metrics event handling has no client attempt data present

with changes in this PR, this error is no longer observed.

2. Unit tests - Existing tests need to pass.
3. Integration tests - Existing tests need to pass.

### Any backward incompatible change? If so, please explain.
NA