Upgrade to golang 1.22 (#1753)
* Upgrade to golang 1.22

* Put back golang v1.21.x in ci workflow

To address the following build errors in ci workflow:

Autobuilder was built with go1.21.7, environment has go1.21.7.
Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps. Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.16.3/x64/codeql/go/tools/autobuild.sh". Exit code was 1 and last log line was: 2024/02/28 18:16:40 Extraction failed: exit status 1. See the logs for more details.

* Revert "Put back golang v1.21.x in ci workflow"

This reverts commit 9b6bbbfaa96266476cac6199791fa0b3ce81e1da.

* Change 1.22 to 1.22.0 everywhere

* one more fix

* one more fix

* add a commit to force presubmit run

* empty commit to force rerun presubmit