Update installing.md
using `brew cask install osxfuse` throws this erro:
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
So changed to `brew install osxfuse` works